// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using familycoins.Data;

namespace familycoins.Migrations
{
    [DbContext(typeof(FamilyCoinsDbContext))]
    partial class FamilyCoinsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("familycoins.Models.FamilyMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<int>("FamilyCoinsScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FamilyMembers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Details = "Eric",
                            FamilyCoinsScore = 500,
                            Name = "Eric"
                        },
                        new
                        {
                            Id = 2,
                            Details = "Adri",
                            FamilyCoinsScore = 500,
                            Name = "Adri"
                        });
                });

            modelBuilder.Entity("familycoins.Models.FamilyPointsTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TypeOfTransaction")
                        .HasColumnType("INTEGER");

                    b.Property<int>("points")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Details = "",
                            Name = "No Hacer Caso",
                            TypeOfTransaction = 0,
                            points = -100
                        },
                        new
                        {
                            Id = 2,
                            Details = "",
                            Name = "No Hacer Caso 2",
                            TypeOfTransaction = 0,
                            points = -100
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
